import Foundation

struct SeedExercise {
    var legacyID: Int
    var name: String
    var muscleGroup: String
    var secondaryMuscleGroups: [String]
    var notes: String
    var weekdayIndex: Int?
    var customSlot: String?
    var sets: Int?
    var reps: Int?
    var seconds: Int?
    var weightKg: Double?
    var synonyms: [String]
    var category: ExerciseCategory = .exercise
}

struct Gainz3Section {
    var headerTitle: String
    var muscleGroup: String
    var category: ExerciseCategory = .exercise
    var exercises: [Gainz3Exercise]
}

struct Gainz3Exercise {
    let displayName: String
    let seedLegacyID: Int
    let sets: Int?
    let reps: Int?
    let seconds: Int?
    let weightKg: Double?
}

enum SeedCatalog {
    static let seedVersion = 3

    static let defaultWeeklySetGoal = 85

    static let defaultTemplateName = "Gymmmmm - science based gainz - Hypertrophy"

    static let gainz3TemplateName = "Science based gainz3"

    static let muscleGroups: [String] = [
        "Biceps",
        "Triceps",
        "Chest",
        "Back",
        "Delts",
        "Legs",
        "Grip / forearms",
        "Neck",
        "Abs"
    ]

    static let exercises: [SeedExercise] = [
        .init(
            legacyID: 1,
            name: "Preacher curls",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 31.8,
            synonyms: []
        ),
        .init(
            legacyID: 2,
            name: "bicep lay back dumbels - 15degr",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 12,
            synonyms: []
        ),
        .init(
            legacyID: 3,
            name: "Close grip pull up/chin-up",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: ["Back"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 4,
            name: "Bicep curls",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 16,
            synonyms: []
        ),
        .init(
            legacyID: 5,
            name: "Bicep rope",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 31,
            synonyms: []
        ),
        .init(
            legacyID: 6,
            name: "Pyramid",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 5,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 7,
            name: "Skull crusher ez bar",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 25,
            synonyms: []
        ),
        .init(
            legacyID: 8,
            name: "Dips / incline dumbel press",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 9,
            name: "Overhead tricep rope",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 25,
            synonyms: []
        ),
        .init(
            legacyID: 10,
            name: "Tricep rope",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: ["Abs"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 35,
            synonyms: []
        ),
        .init(
            legacyID: 11,
            name: "Bench press",
            muscleGroup: "Chest",
            secondaryMuscleGroups: ["Triceps"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 70,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 12,
            name: "Bench press (incline)",
            muscleGroup: "Chest",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 60,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 13,
            name: "Machine/dumbell flies",
            muscleGroup: "Chest",
            secondaryMuscleGroups: ["Biceps"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 18,
            synonyms: []
        ),
        .init(
            legacyID: 14,
            name: "Landmine press (scapula)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 15,
            name: "Face pulls",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 16,
            name: "Deadlift (erectors)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 100,
            synonyms: ["pull from floor", "hip hinge"]
        ),
        .init(
            legacyID: 17,
            name: "Pull ups wide grip",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 18,
            name: "Cable Y Raise (lower traps)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 35,
            synonyms: []
        ),
        .init(
            legacyID: 19,
            name: "Rows",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 40,
            synonyms: ["rowing"]
        ),
        .init(
            legacyID: 20,
            name: "Weighted pull ups",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 7,
            seconds: nil,
            weightKg: 12,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 21,
            name: "Hyperextension low (erectors low)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 22,
            name: "kelso shrugs (upper back) - 5x 12x 100kg",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 100,
            synonyms: []
        ),
        .init(
            legacyID: 23,
            name: "Plate scapular sweep up 5x10x5kgx2",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 5,
            synonyms: []
        ),
        .init(
            legacyID: 24,
            name: "Lateral raises (side delt) / incl. Y raises (dumbels, thumb forward) 5x10x10kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 25,
            name: "Shoulder press / dumbell (front/side delt) below chin - 5x 10x 2x18kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 18,
            synonyms: []
        ),
        .init(
            legacyID: 26,
            name: "Arnold press 10kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 27,
            name: "Shoulder cable stretch/cross over 6kg 10x 5x",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 6,
            synonyms: []
        ),
        .init(
            legacyID: 28,
            name: "Lateral raises (cable, out and back) (rear delts) 5x10x5kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 5,
            synonyms: []
        ),
        .init(
            legacyID: 29,
            name: "Arnold side delt bench",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 30,
            name: "Rear delt machine flies",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 31,
            name: "Seated cable deadlift",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: ["pull from floor", "hip hinge"]
        ),
        .init(
            legacyID: 32,
            name: "Leg press, 5x10x115kg deeep tand 12",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 115,
            synonyms: []
        ),
        .init(
            legacyID: 33,
            name: "Leg curls - 5x10x67kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 67,
            synonyms: []
        ),
        .init(
            legacyID: 34,
            name: "Leg extensions 5x10x70kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 70,
            synonyms: []
        ),
        .init(
            legacyID: 35,
            name: "Squats (deep)- 5x 8x 80kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 80,
            synonyms: ["leg squat"]
        ),
        .init(
            legacyID: 36,
            name: "Zercher squad 40kg 12x5x",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 37,
            name: "Calf raises - 5x 8x 97kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 97,
            synonyms: []
        ),
        .init(
            legacyID: 38,
            name: "Lounges - 5x 12st 60kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 60,
            synonyms: []
        ),
        .init(
            legacyID: 39,
            name: "Curl top 5x12x6kg-max",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 20,
            seconds: nil,
            weightKg: 6,
            synonyms: []
        ),
        .init(
            legacyID: 40,
            name: "Curl bottom 5x18x10kg-max",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 20,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 41,
            name: "Hang / fingers 3x 50-100s / swing bars 5x back n forth",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 50,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 42,
            name: "Towel hang 5x 30s",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 43,
            name: "Falsegrip",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 44,
            name: "Finger push up",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 45,
            name: "Ridge hang",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 46,
            name: "Trap raises 5x14x32kgx2",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 14,
            seconds: nil,
            weightKg: 32,
            synonyms: []
        ),
        .init(
            legacyID: 47,
            name: "Plate on forehead curls",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 48,
            name: "Back head curls",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 49,
            name: "Side",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 50,
            name: "dragon flag",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 51,
            name: "leg raises 5x10x",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 52,
            name: "cable crunches",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 53,
            name: "cable twists 4x 10x 20kg",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 4,
            reps: 10,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 54,
            name: "leg flutters 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 55,
            name: "bicycles  3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 56,
            name: "ab roll out",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 57,
            name: "side plank move 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 58,
            name: "mountain climbers 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 59,
            name: "russian twists  3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 60,
            name: "lay on back shoulder on knees",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 61,
            name: "door arms up (chest)",
            muscleGroup: "Chest",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 62,
            name: "hammies weighted",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: 40,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 63,
            name: "childs pose reach sweep",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 64,
            name: "lying pigeon stretches",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 65,
            name: "door peck minor",
            muscleGroup: "Chest",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 66,
            name: "Neck stretch shoulders-back dumbell assisted",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: 10,
            synonyms: [],
            category: .stretch
        ),
        .init(
            legacyID: 67,
            name: "Serratus anterior push up",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 68,
            name: "Band pull apart black thin",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 4,
            reps: 20,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 69,
            name: "Prone Y raises",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 70,
            name: "Elliptical 10m lvl 15 random hills",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: [],
            category: .cardio
        )
    ]

    // MARK: - Science based gainz3 template

    static let gainz3Sections: [Gainz3Section] = [
        .init(headerTitle: "Biceps", muscleGroup: "Biceps", exercises: [
            .init(displayName: "bicep lay back dumbels - 15degr", seedLegacyID: 2, sets: 5, reps: 12, seconds: nil, weightKg: 10),
            .init(displayName: "Close grip pull up/chin-up", seedLegacyID: 3, sets: 5, reps: 8, seconds: nil, weightKg: nil),
            .init(displayName: "Bicep curls", seedLegacyID: 4, sets: 5, reps: 8, seconds: nil, weightKg: 16),
            .init(displayName: "Preacher curls", seedLegacyID: 1, sets: 5, reps: 8, seconds: nil, weightKg: 31),
            .init(displayName: "Pyramid", seedLegacyID: 6, sets: 5, reps: 5, seconds: nil, weightKg: 25),
            .init(displayName: "Bicep rope", seedLegacyID: 5, sets: 5, reps: 8, seconds: nil, weightKg: 31),
        ]),
        .init(headerTitle: "Triceps", muscleGroup: "Triceps", exercises: [
            .init(displayName: "Skull crusher ez bar", seedLegacyID: 7, sets: 5, reps: 12, seconds: nil, weightKg: 25),
            .init(displayName: "Tricep rope", seedLegacyID: 10, sets: 5, reps: 8, seconds: nil, weightKg: 35),
            .init(displayName: "Overhead tricep rope", seedLegacyID: 9, sets: 5, reps: 10, seconds: nil, weightKg: 25),
            .init(displayName: "Dips / incline dumbel press", seedLegacyID: 8, sets: 5, reps: 10, seconds: nil, weightKg: 40),
        ]),
        .init(headerTitle: "Chest", muscleGroup: "Chest", exercises: [
            .init(displayName: "Bench press", seedLegacyID: 11, sets: 5, reps: 10, seconds: nil, weightKg: 70),
            .init(displayName: "Machine/dumbell flies", seedLegacyID: 13, sets: 5, reps: 8, seconds: nil, weightKg: 18),
            .init(displayName: "Bench press (incline)", seedLegacyID: 12, sets: 5, reps: 8, seconds: nil, weightKg: 60),
        ]),
        .init(headerTitle: "Back", muscleGroup: "Back", exercises: [
            .init(displayName: "kelso shrugs (upper back)", seedLegacyID: 22, sets: 5, reps: 12, seconds: nil, weightKg: 100),
            .init(displayName: "Hyperextension low (erectors low)", seedLegacyID: 21, sets: 5, reps: 12, seconds: nil, weightKg: nil),
            .init(displayName: "Weighted pull ups", seedLegacyID: 20, sets: 5, reps: 7, seconds: nil, weightKg: 10),
            .init(displayName: "Pull ups wide grip", seedLegacyID: 17, sets: 5, reps: 8, seconds: nil, weightKg: nil),
            .init(displayName: "Deadlift (erectors)", seedLegacyID: 16, sets: 5, reps: 8, seconds: nil, weightKg: 100),
            .init(displayName: "Cable Y Raise (lower traps)", seedLegacyID: 18, sets: 5, reps: 12, seconds: nil, weightKg: 35),
            .init(displayName: "Rows", seedLegacyID: 19, sets: 5, reps: 8, seconds: nil, weightKg: 40),
        ]),
        .init(headerTitle: "Delts", muscleGroup: "Delts", exercises: [
            .init(displayName: "Shoulder press / dumbell (front/side delt) below chin", seedLegacyID: 25, sets: 5, reps: 10, seconds: nil, weightKg: 18),
            .init(displayName: "Lateral raises (side delt) / incl. Y raises (dumbels, thumb forward) 5x10x10kg", seedLegacyID: 24, sets: 5, reps: 10, seconds: nil, weightKg: 10),
            .init(displayName: "Shoulder cable stretch/cross over 6kg 10x 5x", seedLegacyID: 27, sets: 5, reps: 10, seconds: nil, weightKg: 6),
            .init(displayName: "Arnold press 10kg", seedLegacyID: 26, sets: 5, reps: 10, seconds: nil, weightKg: 10),
            .init(displayName: "Lateral raises (cable, out and back) (rear delts) 5x10x5kg", seedLegacyID: 28, sets: 5, reps: 10, seconds: nil, weightKg: 5),
            .init(displayName: "Rear delt machine flies", seedLegacyID: 30, sets: nil, reps: nil, seconds: nil, weightKg: nil),
        ]),
        .init(headerTitle: "Legs", muscleGroup: "Legs", exercises: [
            .init(displayName: "Lounges", seedLegacyID: 38, sets: 5, reps: 12, seconds: nil, weightKg: 60),
            .init(displayName: "Leg extensions", seedLegacyID: 34, sets: 5, reps: 10, seconds: nil, weightKg: 70),
            .init(displayName: "Seated cable deadlift", seedLegacyID: 31, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "Leg press deeep tand 12", seedLegacyID: 32, sets: 5, reps: 10, seconds: nil, weightKg: 115),
            .init(displayName: "Calf raises", seedLegacyID: 37, sets: 5, reps: 8, seconds: nil, weightKg: 97),
            .init(displayName: "Zercher squad", seedLegacyID: 36, sets: 5, reps: 12, seconds: nil, weightKg: 40),
            .init(displayName: "Squats (deep)", seedLegacyID: 35, sets: 5, reps: 8, seconds: nil, weightKg: 80),
            .init(displayName: "Leg curls", seedLegacyID: 33, sets: 5, reps: 10, seconds: nil, weightKg: 67),
        ]),
        .init(headerTitle: "Grip / forearms", muscleGroup: "Grip / forearms", exercises: [
            .init(displayName: "Finger push up", seedLegacyID: 44, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "Curl bottom", seedLegacyID: 40, sets: 5, reps: 20, seconds: nil, weightKg: 10),
            .init(displayName: "Hang / fingers", seedLegacyID: 41, sets: 3, reps: nil, seconds: 50, weightKg: nil),
            .init(displayName: "Curl top", seedLegacyID: 39, sets: 5, reps: 20, seconds: nil, weightKg: 6),
            .init(displayName: "Falsegrip", seedLegacyID: 43, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "Towel hang", seedLegacyID: 42, sets: 5, reps: nil, seconds: 30, weightKg: nil),
            .init(displayName: "Ridge hang", seedLegacyID: 45, sets: nil, reps: nil, seconds: nil, weightKg: nil),
        ]),
        .init(headerTitle: "Neck", muscleGroup: "Neck", exercises: [
            .init(displayName: "Plate on forehead curls", seedLegacyID: 47, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "Trap raises", seedLegacyID: 46, sets: 5, reps: 14, seconds: nil, weightKg: 32),
            .init(displayName: "Side", seedLegacyID: 49, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "Back head curls", seedLegacyID: 48, sets: nil, reps: nil, seconds: nil, weightKg: nil),
        ]),
        .init(headerTitle: "Abs", muscleGroup: "Abs", exercises: [
            .init(displayName: "cable twists", seedLegacyID: 53, sets: 4, reps: 10, seconds: nil, weightKg: 20),
            .init(displayName: "russian twists", seedLegacyID: 59, sets: 3, reps: nil, seconds: 45, weightKg: nil),
            .init(displayName: "side plank move", seedLegacyID: 57, sets: 3, reps: nil, seconds: 45, weightKg: nil),
            .init(displayName: "cable crunches", seedLegacyID: 52, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "mountain climbers", seedLegacyID: 58, sets: 3, reps: nil, seconds: 45, weightKg: nil),
            .init(displayName: "leg raises", seedLegacyID: 51, sets: 5, reps: 10, seconds: nil, weightKg: nil),
            .init(displayName: "leg flutters", seedLegacyID: 54, sets: 3, reps: nil, seconds: 45, weightKg: nil),
            .init(displayName: "ab roll out", seedLegacyID: 56, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "dragon flag", seedLegacyID: 50, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "bicycles", seedLegacyID: 55, sets: 3, reps: nil, seconds: 45, weightKg: nil),
        ]),
        .init(headerTitle: "Stretch", muscleGroup: "Legs", category: .stretch, exercises: [
            .init(displayName: "lying pigeon stretches", seedLegacyID: 64, sets: 3, reps: nil, seconds: 30, weightKg: nil),
            .init(displayName: "door peck minor", seedLegacyID: 65, sets: 3, reps: nil, seconds: 30, weightKg: nil),
            .init(displayName: "lay on back shoulder on knees", seedLegacyID: 60, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "childs pose reach sweep", seedLegacyID: 63, sets: nil, reps: nil, seconds: nil, weightKg: nil),
            .init(displayName: "hammies weighted", seedLegacyID: 62, sets: 3, reps: nil, seconds: 30, weightKg: 40),
            .init(displayName: "Neck stretch shoulders-back dumbell assisted", seedLegacyID: 66, sets: 3, reps: nil, seconds: 30, weightKg: 10),
        ]),
        .init(headerTitle: "Scapularis Fixerius", muscleGroup: "Back", exercises: [
            .init(displayName: "Plate scapular sweep up", seedLegacyID: 23, sets: 5, reps: 10, seconds: nil, weightKg: 5),
            .init(displayName: "Face pulls", seedLegacyID: 15, sets: 5, reps: 10, seconds: nil, weightKg: 15),
            .init(displayName: "Landmine press (scapula)", seedLegacyID: 14, sets: 5, reps: 10, seconds: nil, weightKg: 40),
            .init(displayName: "Serratus anterior push up", seedLegacyID: 67, sets: 5, reps: 12, seconds: nil, weightKg: nil),
            .init(displayName: "Band pull apart black thin", seedLegacyID: 68, sets: 4, reps: 20, seconds: nil, weightKg: nil),
            .init(displayName: "Prone Y raises", seedLegacyID: 69, sets: 5, reps: 12, seconds: nil, weightKg: nil),
        ]),
        .init(headerTitle: "Cardio", muscleGroup: "Legs", category: .cardio, exercises: [
            .init(displayName: "Elliptical 10m lvl 15 random hills", seedLegacyID: 70, sets: nil, reps: nil, seconds: nil, weightKg: nil),
        ]),
    ]
}
