import Foundation

struct SeedExercise {
    let legacyID: Int
    let name: String
    let muscleGroup: String
    let secondaryMuscleGroups: [String]
    let notes: String
    let weekdayIndex: Int?
    let customSlot: String?
    let sets: Int?
    let reps: Int?
    let seconds: Int?
    let weightKg: Double?
    let synonyms: [String]
}

enum SeedCatalog {
    static let seedVersion = 2

    static let defaultWeeklySetGoal = 85

    static let defaultTemplateName = "Gymmmmm - science based gainz - Hypertrophy"

    static let muscleGroups: [String] = [
        "Biceps",
        "Triceps",
        "Chest",
        "Back",
        "Delts",
        "Legs",
        "Grip / forearms",
        "Neck",
        "Abs",
        "Stretch"
    ]

    static let exercises: [SeedExercise] = [
        .init(
            legacyID: 1,
            name: "Preacher curls",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 31.8,
            synonyms: []
        ),
        .init(
            legacyID: 2,
            name: "bicep lay back dumbels - 15degr",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 12,
            synonyms: []
        ),
        .init(
            legacyID: 3,
            name: "Close grip pull up/chin-up",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: ["Back"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 4,
            name: "Bicep curls",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 16,
            synonyms: []
        ),
        .init(
            legacyID: 5,
            name: "Bicep rope",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 31,
            synonyms: []
        ),
        .init(
            legacyID: 6,
            name: "Pyramid",
            muscleGroup: "Biceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 5,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 7,
            name: "Skull crusher ez bar",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 25,
            synonyms: []
        ),
        .init(
            legacyID: 8,
            name: "Dips / incline dumbel press",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 9,
            name: "Overhead tricep rope",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 25,
            synonyms: []
        ),
        .init(
            legacyID: 10,
            name: "Tricep rope",
            muscleGroup: "Triceps",
            secondaryMuscleGroups: ["Core"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 35,
            synonyms: []
        ),
        .init(
            legacyID: 11,
            name: "Bench press",
            muscleGroup: "Chest",
            secondaryMuscleGroups: ["Triceps"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 70,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 12,
            name: "Bench press (incline)",
            muscleGroup: "Chest",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 60,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 13,
            name: "Machine/dumbell flies",
            muscleGroup: "Chest",
            secondaryMuscleGroups: ["Bisceps"],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 18,
            synonyms: []
        ),
        .init(
            legacyID: 14,
            name: "Landmine press (scapula)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 15,
            name: "Face pulls",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 16,
            name: "Deadlift (erectors)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 100,
            synonyms: ["pull from floor", "hip hinge"]
        ),
        .init(
            legacyID: 17,
            name: "Pull ups wide grip",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 18,
            name: "Cable Y Raise (lower traps)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 35,
            synonyms: []
        ),
        .init(
            legacyID: 19,
            name: "Rows",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 40,
            synonyms: ["rowing"]
        ),
        .init(
            legacyID: 20,
            name: "Weighted pull ups",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 7,
            seconds: nil,
            weightKg: 12,
            synonyms: ["chin up"]
        ),
        .init(
            legacyID: 21,
            name: "Hyperextension low (erectors low)",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 22,
            name: "kelso shrugs (upper back) - 5x 12x 100kg",
            muscleGroup: "Back",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 100,
            synonyms: []
        ),
        .init(
            legacyID: 23,
            name: "Plate scapular sweep up 5x10x5kgx2",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 5,
            synonyms: []
        ),
        .init(
            legacyID: 24,
            name: "Lateral raises (side delt) / incl. Y raises (dumbels, thumb forward) 5x10x10kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 25,
            name: "Shoulder press / dumbell (front/side delt) below chin - 5x 10x 2x18kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 18,
            synonyms: []
        ),
        .init(
            legacyID: 26,
            name: "Arnold press 10kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 27,
            name: "Shoulder cable stretch/cross over 6kg 10x 5x",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 6,
            synonyms: []
        ),
        .init(
            legacyID: 28,
            name: "Lateral raises (cable, out and back) (rear delts) 5x10x5kg",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 5,
            synonyms: []
        ),
        .init(
            legacyID: 29,
            name: "Arnold side delt bench",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: ["chest press"]
        ),
        .init(
            legacyID: 30,
            name: "Rear delt machine flies",
            muscleGroup: "Delts",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 31,
            name: "Seated cable deadlift",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: ["pull from floor", "hip hinge"]
        ),
        .init(
            legacyID: 32,
            name: "Leg press, 5x10x115kg deeep tand 12",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 115,
            synonyms: []
        ),
        .init(
            legacyID: 33,
            name: "Leg curls - 5x10x67kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 67,
            synonyms: []
        ),
        .init(
            legacyID: 34,
            name: "Leg extensions 5x10x70kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: 70,
            synonyms: []
        ),
        .init(
            legacyID: 35,
            name: "Squats (deep)- 5x 8x 80kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 80,
            synonyms: ["leg squat"]
        ),
        .init(
            legacyID: 36,
            name: "Zercher squad 40kg 12x5x",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 37,
            name: "Calf raises - 5x 8x 97kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 8,
            seconds: nil,
            weightKg: 97,
            synonyms: []
        ),
        .init(
            legacyID: 38,
            name: "Lounges - 5x 12st 60kg",
            muscleGroup: "Legs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 12,
            seconds: nil,
            weightKg: 60,
            synonyms: []
        ),
        .init(
            legacyID: 39,
            name: "Curl top 5x12x6kg-max",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 20,
            seconds: nil,
            weightKg: 6,
            synonyms: []
        ),
        .init(
            legacyID: 40,
            name: "Curl bottom 5x18x10kg-max",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 20,
            seconds: nil,
            weightKg: 10,
            synonyms: []
        ),
        .init(
            legacyID: 41,
            name: "Hang / fingers 3x 50-100s / swing bars 5x back n forth",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 50,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 42,
            name: "Towel hang 5x 30s",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 43,
            name: "Falsegrip",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 44,
            name: "Finger push up",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 45,
            name: "Ridge hang",
            muscleGroup: "Grip / forearms",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 46,
            name: "Trap raises 5x14x32kgx2",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 14,
            seconds: nil,
            weightKg: 32,
            synonyms: []
        ),
        .init(
            legacyID: 47,
            name: "Plate on forehead curls",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 48,
            name: "Back head curls",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 49,
            name: "Side",
            muscleGroup: "Neck",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 50,
            name: "dragon flag",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 51,
            name: "leg raises 5x10x",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 5,
            reps: 10,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 52,
            name: "cable crunches",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 53,
            name: "cable twists 4x 10x 20kg",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 4,
            reps: 10,
            seconds: nil,
            weightKg: 20,
            synonyms: []
        ),
        .init(
            legacyID: 54,
            name: "leg flutters 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 55,
            name: "bicycles  3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 56,
            name: "ab roll out",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 57,
            name: "side plank move 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 58,
            name: "mountain climbers 3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 59,
            name: "russian twists  3x 45s",
            muscleGroup: "Abs",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 45,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 60,
            name: "lay on back shoulder on knees",
            muscleGroup: "Stretch",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 61,
            name: "door arms up (chest)",
            muscleGroup: "Stretch",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 62,
            name: "hammies weighted",
            muscleGroup: "Stretch",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: 40,
            synonyms: []
        ),
        .init(
            legacyID: 63,
            name: "childs pose reach sweep",
            muscleGroup: "Stretch",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: nil,
            reps: nil,
            seconds: nil,
            weightKg: nil,
            synonyms: []
        ),
        .init(
            legacyID: 64,
            name: "lying pigeon stretches",
            muscleGroup: "Stretch",
            secondaryMuscleGroups: [],
            notes: "",
            weekdayIndex: nil,
            customSlot: nil,
            sets: 3,
            reps: nil,
            seconds: 30,
            weightKg: nil,
            synonyms: []
        )
    ]
}
